### ISSUE TITLE
프로젝트 환경 세팅

### ISSUE THREAD

**Issue by jungmir** [HelloPy-Korea/hellopy-backend#1]
# 환경 세팅

- 개발 환경 세팅
  - 브랜치 전략, 컨벤션 등 원활한 개발을 위해 필요한 전반적인 환경 구성

- 빌드 환경 세팅
  - 개발이 완료된 코드에 대한 검증 및 배포 결과물을 만들기 위한 환경 구성

- 배포 환경 세팅
  - 빌드가 완료된 애플리케이션을 손쉽게 배포하고 관리하기 위한 환경 구성

**Comment by YongJun-Lee-98** [comment]
# 배포 과정

Workflow
1. 테스트 이후 문제가 없다면 
2. develop 브랜치에 feature 브랜치를 merge(병합)
3. 테스
4. develop 브랜치 푸시

-> docker 빌드 이후 ghcr.io 에 Docker 컨테이너 푸시

Github Actions 실행
선행 사항 : develop 브랜치에서 merge 완료 시

## Stable 버전 관리  
git tag stable push로 stable 버전을 관리합니다.
Docker 이미지에 태그 적용
docker tag ghcr.io/USERNAME/myapp:stable

롤백 - 안정 버전으로 즉시 복원
ssh user@server "docekr pull ghcr.io/USERNAME/myapp:stable

feature 브랜치 생성 -> develop 병합 -> main 병합
                                |-> PR  생성       |-> PR 생성

develop 병합 | main 병합 시에 
1. 각각의 github actions을 통해 머지 완료 시
2. 도커 이미지 다운로드 (ghcr.io)
3. 테스트 실행
4. success : stable 태그 등록
5. fail : 롤백 진행 

-----
이후 내용은 도커 Hub 기준이였지만 ghcr.io 로 변경 하고 다시 공유하겠습니다.

## 롤백 과정 (개발자 시점에서의 주요 내용)

### **1. 배포 후 문제가 발생한 경우 (테스트 실패 또는 서비스 장애 발생)**
- 배포 후 문제가 발생하면 개발자는 **즉시 롤백을 결정**해야 함
- 롤백 전략은 세 가지 방식으로 진행됨: `Git 롤백`, `Docker 컨테이너 롤백`, `CI/CD 롤백`
- 각 롤백은 필요 판단시 .bashrc에 함수형으로 등록 예정
### **2. Git 롤백 (`reset --hard`, `revert`)**
**사용 시점:**
- `develop` 브랜치의 코드 변경이 잘못되었을 때
- 특정 버전(`v1.1.0`)에서 문제가 발생하여 `v1.0.0`으로 되돌려야 할 때

📌 **Git 롤백 명령어:**
```bash
git checkout develop
git reset --hard v1.0.0  # v1.0.0 버전으로 강제 롤백
git push origin develop --force  # 강제 푸시 (주의)
```

✅ **결과:** `develop` 브랜치가 이전 버전(v1.0.0)으로 복구됨
### **3. Docker 컨테이너 롤백**
**사용 시점:**
- `main` 브랜치에서 배포 성공했지만, 서비스 장애가 발생한 경우
- `v1.1.0`을 배포했으나 문제가 있어 `v1.0.0`으로 즉시 복구해야 할 때

📌 **Docker 롤백 명령어:**
```bash
ssh user@server "docker stop myapp && docker rm myapp"
ssh user@server "docker run -d -p 8000:8000 --name myapp myrepo/myapp:v1.0.0"
```
✅ **결과:** 최신 컨테이너가 중단되고 `v1.0.0` 버전이 다시 실행됨

### **4. CI/CD 롤백 (GitHub Actions 활용)**
#### **배포 실패 시 자동 롤백**
**사용 시점:**
- CI/CD 배포가 실패했을 때 자동으로 롤백하도록 설정 가능

📌 **GitHub Actions에서 배포 실패 시 자동 롤백**
```yaml
- name: Deploy to Server
  run: |
    ssh user@server "docker pull myrepo/myapp:latest && docker stop myapp && docker rm myapp && docker run -d -p 8000:8000 --name myapp myrepo/myapp:latest"
  continue-on-error: true

- name: Rollback on Failure
  if: failure()
  run: |
    ssh user@server "docker pull myrepo/myapp:v1.0.0 && docker stop myapp && docker rm myapp && docker run -d -p 8000:8000 --name myapp myrepo/myapp:v1.0.0"
```
✅ **결과:**
- 배포 실패 시 자동으로 `v1.0.0` 버전으로 롤백됨

#### **배포 성공 후 서비스 장애로 롤백이 필요한 경우**
**사용 시점:**
- 배포는 성공했으나 이후 서비스 장애로 인해 특정 버전(`v1.0.0`)으로 롤백해야 하는 경우

📌 **GitHub Actions에서 특정 버전 롤백 실행 (수동 트리거 사용)**
```yaml
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Rollback to specific version"
        required: true
        default: "v1.0.0"
```
✅ **결과:**
- GitHub Actions 실행 시, `v1.0.0` 또는 다른 버전을 선택하여 롤백 가능
- 선택한 버전의 Git 코드 기반으로 Docker 이미지를 다시 빌드하고 배포

---

## 3️⃣ Stable 버전 관리
배포가 안정적으로 완료된 시점에 해당 버전을 `stable` 태그로 지정하여, **나중에 문제가 발생했을 때 빠르게 롤백**할 수 있습니다.

### **1. Git에서 `stable` 태그 관리**
```bash
git tag -f stable

git push origin stable --force
```
- `-f` 옵션을 사용하면 기존 태그를 업데이트할 수 있습니다.
- `stable` 태그를 항상 최신 안정 커밋에 맞춰 갱신해두면, 롤백할 때 이 태그로 빠르게 복원 가능합니다.

### **2. Docker 이미지에 `stable` 태그 적용**
```bash
# Docker 이미지 빌드 후 stable 태그도 추가

docker build -t myrepo/myapp:latest .
docker tag myrepo/myapp:latest myrepo/myapp:stable

docker push myrepo/myapp:latest

docker push myrepo/myapp:stable
```
- `stable` 태그가 달린 이미지는 **항상 마지막으로 검증된 안정 버전**을 의미

### **3. `stable` 태그를 이용한 롤백**
```bash
# 서버에서 stable 태그 이미지를 사용해 재배포
ssh user@server "docker pull myrepo/myapp:stable && docker stop myapp && docker rm myapp && docker run -d -p 8000:8000 --name myapp myrepo/myapp:stable"
```
- 문제가 발생했을 때 **안정 버전으로 즉시 복원** 가능
